package hclmap

import (
	"errors"
	"reflect"
	"strings"
	"testing"

	"github.com/centopw/nodr/internal/lens"
)

type testResource struct {
	Name    string     `hcl:"name"`
	Size    int        `hcl:"size"`
	Enabled *bool      `hcl:"enabled,optional"`
	Note    string     `hcl:"note,optional"`
	Tags    []string   `hcl:"tags,set,optional"`
	CPU     *testCPU   `hcl:"cpu,block"`
	Agent   *testAgent `hcl:"agent,block,optional"`
	Disks   []testDisk `hcl:"disk,block"`
}

type testCPU struct {
	Cores int    `hcl:"cores"`
	Type  string `hcl:"type,optional"`
}

type testAgent struct {
	Enabled bool `hcl:"enabled"`
}

type testDisk struct {
	Size    int    `hcl:"size"`
	Storage string `hcl:"storage"`
	SSD     bool   `hcl:"ssd,optional"`
}

var target = Target{Type: "resource", Labels: []string{"example_vm", "web"}}

func boolPtr(b bool) *bool { return &b }

func sample() testResource {
	return testResource{
		Name:    "web",
		Size:    4096,
		Enabled: boolPtr(true),
		Tags:    []string{"a", "b"},
		CPU:     &testCPU{Cores: 2, Type: "host"},
		Disks:   []testDisk{{Size: 32, Storage: "local"}, {Size: 64, Storage: "ceph", SSD: true}},
	}
}

const sampleHCL = `# nodr:managed vm/web
resource "example_vm" "web" {
  name    = "web"
  size    = 4096
  enabled = true
  tags    = ["a", "b"]

  cpu {
    cores = 2
    type  = "host"
  }

  disk {
    size    = 32
    storage = "local"
  }

  disk {
    size    = 64
    storage = "ceph"
    ssd     = true
  }
}
`

func TestRender(t *testing.T) {
	got, err := Render(target, "nodr:managed vm/web", sample())
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != sampleHCL {
		t.Errorf("Render =\n%s\nwant\n%s", got, sampleHCL)
	}
}

func TestLiftRenderedCode(t *testing.T) {
	got, states, err := Lift([]byte(sampleHCL), "vm.tf", target, testResource{})
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(got, sample()) {
		t.Errorf("Lift = %+v, want %+v", got, sample())
	}
	for _, s := range states {
		if s.Owner != lens.Synced {
			t.Errorf("%s is %s (%s), want synced", s.Path, s.Owner, s.Reason)
		}
	}
	lines := map[string]int{}
	for _, s := range states {
		lines[s.Path] = s.Line
	}
	for path, want := range map[string]int{"name": 3, "cpu.cores": 9, "disk[1].ssd": 21, "note": 0} {
		if lines[path] != want {
			t.Errorf("line of %s = %d, want %d", path, lines[path], want)
		}
	}
}

func TestLiftClassifiesOwnership(t *testing.T) {
	src := `resource "example_vm" "web" {
  name = "web-${var.suffix}"
  size = 2048 # nodr:keep
  note = upper("x")
  tags = null
  smbios_serial = "LIC-1"
  lifecycle {
    ignore_changes = [size]
  }
  dynamic "disk" {
    for_each = var.disks
    content {
      size    = disk.value
      storage = "local"
    }
  }
  cpu {
    cores = "four"
  }
  cpu {
    cores = 2
  }
}
`
	base := sample()
	got, states, err := Lift([]byte(src), "vm.tf", target, base)
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]string{
		"name":          "code-owned: set by an expression",
		"size":          "code-owned: pinned with nodr:keep",
		"enabled":       "synced",
		"note":          "code-owned: set by an expression",
		"tags":          "synced",
		"smbios_serial": "extension",
		"lifecycle":     "extension",
		"disk":          "code-owned: generated by a dynamic block",
		"disk.size":     "code-owned: generated by a dynamic block",
		"cpu":           "code-owned: the block is defined more than once",
		"cpu.cores":     "code-owned: the block is defined more than once",
		"agent":         "synced",
	}
	assertStates(t, states, want)
	if got.Name != base.Name || got.Size != base.Size || got.CPU.Cores != base.CPU.Cores {
		t.Errorf("code-owned fields must keep the base values, got %+v", got)
	}
	if got.Enabled != nil || got.Tags != nil {
		t.Errorf("absent and null optional attributes lift to zero values, got enabled=%v tags=%v", got.Enabled, got.Tags)
	}
	if len(got.Disks) != len(base.Disks) {
		t.Errorf("disks generated by a dynamic block keep the base values, got %d", len(got.Disks))
	}
}

func TestLiftInvalidLiteralAndAbsentRequired(t *testing.T) {
	src := `resource "example_vm" "web" {
  size = "big"
  cpu {
    cores = 2
  }
}
`
	_, states, err := Lift([]byte(src), "vm.tf", target, sample())
	if err != nil {
		t.Fatal(err)
	}
	assertStates(t, states, map[string]string{
		"name":      "code-owned: not set in code, so the provider default applies",
		"size":      "code-owned: the value is not a valid number",
		"cpu.cores": "synced",
		"cpu.type":  "synced",
		"disk":      "synced",
	})
}

func TestLiftMetaArguments(t *testing.T) {
	src := "resource \"example_vm\" \"web\" {\n  count = 2\n  name  = \"web\"\n}\n"
	got, states, err := Lift([]byte(src), "vm.tf", target, sample())
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(got, sample()) {
		t.Error("a resource with count must keep the base values")
	}
	for _, s := range states {
		if s.Owner != lens.CodeOwned || s.Reason != ReasonMetaArgument {
			t.Errorf("%s = %s (%s), want code-owned because of count", s.Path, s.Owner, s.Reason)
		}
	}
	out, err := Put([]byte(src), "vm.tf", target, testResource{Name: "other"})
	if err != nil || string(out) != src {
		t.Errorf("Put changed a resource with count: %v\n%s", err, out)
	}
}

func TestLiftErrors(t *testing.T) {
	if _, _, err := Lift([]byte("resource {"), "vm.tf", target, sample()); err == nil {
		t.Error("Lift of invalid HCL succeeded")
	}
	_, _, err := Lift([]byte(`resource "example_vm" "other" {}`), "vm.tf", target, sample())
	if !errors.Is(err, ErrTargetNotFound) {
		t.Errorf("Lift of a missing block: err = %v, want ErrTargetNotFound", err)
	}
}

func TestPutChangesOnlyWhatDiffers(t *testing.T) {
	src := `# nodr:managed vm/web
resource "example_vm" "web" {
  name    = "web" # the public name
  size    = 4096
  enabled = true
  tags    = ["b", "a"]
  extra   = "kept" # an extension

  cpu {
    cores = var.cores
    type  = "host"
  }

  disk {
    size    = 32
    storage = "local"
  }

  disk {
    size    = 64
    storage = "ceph"
    ssd     = true
  }
}
`
	desired := sample()
	desired.Size = 8192
	desired.CPU.Cores = 16
	out, err := Put([]byte(src), "vm.tf", target, desired)
	if err != nil {
		t.Fatal(err)
	}
	want := strings.Replace(src, "size    = 4096", "size    = 8192", 1)
	if string(out) != want {
		t.Errorf("Put =\n%s\nwant\n%s", out, want)
	}
}

func TestPutIsIdentityWhenNothingChanged(t *testing.T) {
	src := "resource \"example_vm\" \"web\" {\n    name=\"web\"   # odd formatting\n  size = 4096\n  enabled = true\n  tags = [\"a\",\"b\"]\n  cpu {\n  cores=2\n  type = \"host\"\n}\n  disk {\n    size = 32\n    storage = \"local\"\n  }\n  disk {\n    size = 64\n    storage = \"ceph\"\n    ssd = true\n  }\n}\n"
	out, err := Put([]byte(src), "vm.tf", target, sample())
	if err != nil {
		t.Fatal(err)
	}
	if string(out) != src {
		t.Errorf("Put changed code whose values already match:\n%s", out)
	}
}

func TestPutInsertsAndRemoves(t *testing.T) {
	desired := sample()
	desired.Enabled = nil
	desired.Note = "hello"
	desired.Tags = nil
	desired.Agent = &testAgent{Enabled: true}
	desired.Disks = append(desired.Disks, testDisk{Size: 8, Storage: "local"})
	out, err := Put([]byte(sampleHCL), "vm.tf", target, desired)
	if err != nil {
		t.Fatal(err)
	}
	want := `# nodr:managed vm/web
resource "example_vm" "web" {
  name = "web"
  size = 4096
  note = "hello"

  cpu {
    cores = 2
    type  = "host"
  }

  agent {
    enabled = true
  }

  disk {
    size    = 32
    storage = "local"
  }

  disk {
    size    = 64
    storage = "ceph"
    ssd     = true
  }

  disk {
    size    = 8
    storage = "local"
  }
}
`
	if string(out) != want {
		t.Errorf("Put =\n%s\nwant\n%s", out, want)
	}

	// Removing the agent and the extra disk again restores the original.
	back, err := Put(out, "vm.tf", target, sample())
	if err != nil {
		t.Fatal(err)
	}
	if string(back) != sampleHCL {
		t.Errorf("Put back =\n%s\nwant\n%s", back, sampleHCL)
	}
}

func TestPutReportsConflicts(t *testing.T) {
	src := strings.Replace(sampleHCL, "    ssd     = true\n", "    ssd     = true\n    cache   = \"writeback\"\n", 1)
	desired := sample()
	desired.Disks = desired.Disks[:1]
	_, err := Put([]byte(src), "vm.tf", target, desired)
	var conflict *ConflictError
	if !errors.As(err, &conflict) || len(conflict.Paths) != 1 || conflict.Paths[0] != "disk[1]" {
		t.Errorf("Put error = %v, want a conflict for disk[1]", err)
	}
}

func TestPutKeepsUnformattedFilesUnformatted(t *testing.T) {
	src := "resource \"example_vm\" \"web\" {\n  name=\"web\"\n  size = 1\n  cpu {\n    cores = 2\n  }\n}\n"
	desired := testResource{Name: "web", Size: 1, CPU: &testCPU{Cores: 2}, Note: "x"}
	out, err := Put([]byte(src), "vm.tf", target, desired)
	if err != nil {
		t.Fatal(err)
	}
	want := "resource \"example_vm\" \"web\" {\n  name=\"web\"\n  size = 1\n  note = \"x\"\n  cpu {\n    cores = 2\n  }\n}\n"
	if string(out) != want {
		t.Errorf("Put =\n%q\nwant\n%q", out, want)
	}
}

func TestPutEditsHandFormattedFilesInPlace(t *testing.T) {
	src := "# servers\nresource \"example_vm\" \"web\" {\n  name=\"web\"   # the name\n  size =    1\n  # temporary\n  enabled=true\n  cpu {\n    cores=2\n  }\n}\n\nresource \"example_vm\" \"db\" {\n  name=\"db\"\n}\n"
	desired := testResource{Name: "www", Size: 1, CPU: &testCPU{Cores: 4}}
	out, err := Put([]byte(src), "vm.tf", target, desired)
	if err != nil {
		t.Fatal(err)
	}
	want := "# servers\nresource \"example_vm\" \"web\" {\n  name=\"www\"   # the name\n  size =    1\n  cpu {\n    cores=4\n  }\n}\n\nresource \"example_vm\" \"db\" {\n  name=\"db\"\n}\n"
	if string(out) != want {
		t.Errorf("Put =\n%s\nwant\n%s", out, want)
	}
}

func TestPutSpreadsSingleLineBlocks(t *testing.T) {
	src := "resource \"example_vm\" \"web\" {\n  name = \"web\"\n  size = 1\n\n  cpu { cores = 2 }\n\n  agent { enabled = true }\n}\n"
	tests := []struct {
		name    string
		desired testResource
		want    string
	}{
		{
			name:    "attribute",
			desired: testResource{Name: "web", Size: 1, CPU: &testCPU{Cores: 2, Type: "host"}, Agent: &testAgent{Enabled: true}},
			want:    "resource \"example_vm\" \"web\" {\n  name = \"web\"\n  size = 1\n\n  cpu {\n    cores = 2\n    type  = \"host\"\n  }\n\n  agent { enabled = true }\n}\n",
		},
		{
			name:    "value",
			desired: testResource{Name: "web", Size: 1, CPU: &testCPU{Cores: 8}, Agent: &testAgent{}},
			want:    "resource \"example_vm\" \"web\" {\n  name = \"web\"\n  size = 1\n\n  cpu { cores = 8 }\n\n  agent { enabled = false }\n}\n",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			out, err := Put([]byte(src), "vm.tf", target, tt.desired)
			if err != nil {
				t.Fatal(err)
			}
			if string(out) != tt.want {
				t.Errorf("Put =\n%s\nwant\n%s", out, tt.want)
			}
		})
	}

	// An empty single-line block gets its first attribute, and a
	// single-line block that loses its only attribute stays.
	src = "resource \"example_vm\" \"web\" {\n  name=\"web\"\n  size=1\n  cpu {}\n  agent { enabled = true }\n}\n"
	type optionalAgent struct {
		Enabled *bool `hcl:"enabled,optional"`
	}
	desired := struct {
		Name  string         `hcl:"name"`
		Size  int            `hcl:"size"`
		CPU   *testCPU       `hcl:"cpu,block"`
		Agent *optionalAgent `hcl:"agent,block"`
	}{Name: "web", Size: 1, CPU: &testCPU{Type: "host"}, Agent: &optionalAgent{}}
	out, err := Put([]byte(src), "vm.tf", target, desired)
	if err != nil {
		t.Fatal(err)
	}
	want := "resource \"example_vm\" \"web\" {\n  name=\"web\"\n  size=1\n  cpu {\n    type = \"host\"\n  }\n  agent {  }\n}\n"
	if string(out) != want {
		t.Errorf("Put =\n%s\nwant\n%s", out, want)
	}
}

func TestPutInsertsAfterARemovedBlock(t *testing.T) {
	type item struct {
		N int `hcl:"n"`
	}
	type note struct {
		Text string `hcl:"text"`
	}
	type resource struct {
		Items []item `hcl:"item,block"`
		Note  *note  `hcl:"note,block,optional"`
	}
	// The blank line after the second item, which goes with it, holds
	// spaces.
	src := "resource \"example_vm\" \"web\" {\n  item {\n    n = 1\n  }\n  item {\n    n = 2\n  }\n      \n}\n"
	out, err := Put([]byte(src), "vm.tf", target, resource{Items: []item{{N: 1}}, Note: &note{Text: "x"}})
	if err != nil {
		t.Fatal(err)
	}
	want := "resource \"example_vm\" \"web\" {\n  item {\n    n = 1\n  }\n\n  note {\n    text = \"x\"\n  }\n}\n"
	if string(out) != want {
		t.Errorf("Put =\n%q\nwant\n%q", out, want)
	}
}

func TestChanged(t *testing.T) {
	a := sample()
	b := sample()
	b.CPU = &testCPU{Cores: 3, Type: "host"}
	b.Tags = []string{"b", "a"}
	b.Disks = b.Disks[:1]
	b.Agent = &testAgent{}
	got := strings.Join(Changed(a, b), ",")
	if want := "cpu.cores,agent,disk"; got != want {
		t.Errorf("Changed = %s, want %s", got, want)
	}
	if Changed(a, sample()) != nil {
		t.Error("Changed of equal values is not empty")
	}
}

func TestSchemaErrors(t *testing.T) {
	type badOption struct {
		A string `hcl:"a,weird"`
	}
	type badType struct {
		A float64 `hcl:"a"`
	}
	type badBlock struct {
		A string `hcl:"a,block"`
	}
	type dupName struct {
		A string `hcl:"a"`
		B string `hcl:"a"`
	}
	for _, v := range []any{badOption{}, badType{}, badBlock{}, dupName{}, 3} {
		if _, err := schemaOf(reflect.TypeOf(v)); err == nil {
			t.Errorf("schemaOf(%T) succeeded", v)
		}
	}
}

func assertStates(t *testing.T, states []State, want map[string]string) {
	t.Helper()
	got := map[string]string{}
	for _, s := range states {
		desc := s.Owner.String()
		if s.Reason != "" {
			desc += ": " + s.Reason
		}
		got[s.Path] = desc
	}
	for path, w := range want {
		if got[path] != w {
			t.Errorf("%s = %q, want %q", path, got[path], w)
		}
	}
}

func TestPutWithKeep(t *testing.T) {
	desired := sample()
	desired.CPU.Type = "qemu64"
	desired.Disks = desired.Disks[:1]
	keep := map[string]bool{"cpu.type": true}
	out, err := PutWith([]byte(sampleHCL), "vm.tf", target, desired, Options{Keep: keep})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(out), `type  = "host"`) || strings.Contains(string(out), "qemu64") {
		t.Errorf("a kept attribute was changed:\n%s", out)
	}
	if strings.Count(string(out), "disk {") != 1 {
		t.Errorf("the second disk was not removed:\n%s", out)
	}

	keep = map[string]bool{"disk[1].ssd": true}
	_, err = PutWith([]byte(sampleHCL), "vm.tf", target, desired, Options{Keep: keep})
	var conflict *ConflictError
	if !errors.As(err, &conflict) || conflict.Paths[0] != "disk[1]" {
		t.Errorf("removing a block with a kept attribute: err = %v, want a conflict", err)
	}
}

func TestPutKeepsWholeBlocks(t *testing.T) {
	desired := sample()
	desired.Disks = desired.Disks[:1]
	desired.CPU.Cores = 8
	out, err := PutWith([]byte(sampleHCL), "vm.tf", target, desired, Options{Keep: map[string]bool{"disk[1]": true, "cpu": true}})
	if err != nil {
		t.Fatal(err)
	}
	if string(out) != sampleHCL {
		t.Errorf("kept blocks were changed:\n%s", out)
	}
}
