package hclmap

import (
	"bytes"
	"errors"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"testing"

	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclsyntax"
	"pgregory.net/rapid"

	"github.com/centopw/nodr/internal/lens"
)

// These property tests check the lens laws of design §4.5 for the HCL
// engine:
//
//   - creation consistency: lift(render(v)) = v, and every field is synced
//   - stability (GetPut):   put(lift(c), c) = c for any code c
//   - fidelity (PutGet):    lift(put(v, c)) = v on synced fields
//
// Code is generated by rendering a random value and then applying random
// edits of the kind a person makes in an editor.

func genResource(t *rapid.T) testResource {
	r := testResource{
		Name: rapid.StringMatching(`[a-z][a-z0-9-]{0,8}`).Draw(t, "name"),
		Size: rapid.IntRange(0, 1<<20).Draw(t, "size"),
		CPU: &testCPU{
			Cores: rapid.IntRange(1, 64).Draw(t, "cores"),
			Type:  rapid.SampledFrom([]string{"", "host", "x86-64-v2-AES"}).Draw(t, "cpuType"),
		},
		Note: rapid.SampledFrom([]string{"", "hello", `with "quotes"`, "two\nlines", "${literal}"}).Draw(t, "note"),
	}
	if rapid.Bool().Draw(t, "hasEnabled") {
		r.Enabled = boolPtr(rapid.Bool().Draw(t, "enabled"))
	}
	if tags := rapid.SliceOfDistinct(rapid.StringMatching(`[a-z]{1,5}`), func(s string) string { return s }).Draw(t, "tags"); len(tags) > 0 {
		r.Tags = tags
	}
	if rapid.Bool().Draw(t, "hasAgent") {
		r.Agent = &testAgent{Enabled: rapid.Bool().Draw(t, "agentEnabled")}
	}
	for range rapid.IntRange(0, 3).Draw(t, "disks") {
		r.Disks = append(r.Disks, testDisk{
			Size:    rapid.IntRange(1, 1000).Draw(t, "diskSize"),
			Storage: rapid.SampledFrom([]string{"local", "ceph"}).Draw(t, "storage"),
			SSD:     rapid.Bool().Draw(t, "ssd"),
		})
	}
	return r
}

var (
	attrLine     = regexp.MustCompile(`^(\s*)([a-z_]+)(\s*)=(\s*)(.*)$`)
	numberLine   = regexp.MustCompile(`^(\s*(?:size|cores)\s*=\s*)\d+$`)
	optionalLine = regexp.MustCompile(`^\s*(note|enabled|tags|ssd|type)\s*=`)
	blockOpen    = regexp.MustCompile(`^\s*[a-z_]+ \{$`)

	// handFormatted marks the lines that mutate formats by hand, which
	// handFormattedLine matches as long as the formatting is kept.
	handFormatted     = "# own style"
	handFormattedLine = regexp.MustCompile(`^\s*[a-z_]+=\S`)
)

// mutate applies random edits to the lines of a rendered block. Edits that
// would make the code invalid are skipped.
func mutate(t *rapid.T, src []byte) []byte {
	lines := strings.Split(strings.TrimSuffix(string(src), "\n"), "\n")
	for i := range rapid.IntRange(0, 6).Draw(t, "edits") {
		n := len(lines)
		if n < 3 {
			break
		}
		at := rapid.IntRange(1, n-2).Draw(t, fmt.Sprintf("line%d", i))
		switch rapid.IntRange(0, 8).Draw(t, fmt.Sprintf("edit%d", i)) {
		case 0: // change a number
			if m := numberLine.FindStringSubmatch(lines[at]); m != nil {
				lines[at] = m[1] + fmt.Sprint(rapid.IntRange(1, 99).Draw(t, "number"))
			}
		case 1: // use an expression
			if m := attrLine.FindStringSubmatch(lines[at]); m != nil && !strings.Contains(m[5], "[") && !strings.Contains(m[5], "\\n") {
				lines[at] = m[1] + m[2] + m[3] + "=" + m[4] + "var.v" + fmt.Sprint(at)
			}
		case 2: // pin a literal
			if attrLine.MatchString(lines[at]) {
				lines[at] += " # nodr:keep"
			}
		case 3: // add an extension attribute
			lines = insertLines(lines, 1, `  extra = "kept"`)
		case 4: // add an extension block
			lines = insertLines(lines, n-1, "", "  smbios {", `    serial = "LIC-1"`, "  }")
		case 5: // add a comment
			lines = insertLines(lines, 1, "  # a comment written by hand")
		case 6: // drop an optional attribute
			if optionalLine.MatchString(lines[at]) {
				lines = append(lines[:at], lines[at+1:]...)
			}
		case 7: // change the formatting
			if m := attrLine.FindStringSubmatch(lines[at]); m != nil {
				lines[at] = m[1] + m[2] + "=" + m[5] + " " + handFormatted
			}
		case 8: // write a block with one attribute on one line
			if at+2 < n && blockOpen.MatchString(lines[at]) && attrLine.MatchString(lines[at+1]) &&
				!strings.Contains(lines[at+1], "#") && strings.TrimSpace(lines[at+2]) == "}" {
				lines[at] += " " + strings.TrimSpace(lines[at+1]) + " }"
				lines = append(lines[:at+1], lines[at+3:]...)
			}
		}
	}
	out := []byte(strings.Join(lines, "\n") + "\n")
	if _, diags := hclsyntax.ParseConfig(out, "x.tf", hcl.InitialPos); diags.HasErrors() {
		return src
	}
	return out
}

func insertLines(lines []string, at int, add ...string) []string {
	out := append([]string{}, lines[:at]...)
	out = append(out, add...)
	return append(out, lines[at:]...)
}

func TestLawCreationConsistency(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		v := genResource(t)
		src, err := Render(target, "", v)
		if err != nil {
			t.Fatal(err)
		}
		got, states, err := Lift(src, "x.tf", target, testResource{})
		if err != nil {
			t.Fatalf("Lift: %v\n%s", err, src)
		}
		if !reflect.DeepEqual(got, v) {
			t.Fatalf("lift(render(v)) = %+v, want %+v\n%s", got, v, src)
		}
		for _, s := range states {
			if s.Owner != lens.Synced {
				t.Fatalf("%s is %s after rendering, want synced", s.Path, s.Owner)
			}
		}
	})
}

func TestLawStability(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		src := mutate(t, mustRender(t, genResource(t)))
		lifted, _, err := Lift(src, "x.tf", target, genResource(t))
		if err != nil {
			t.Fatalf("Lift: %v\n%s", err, src)
		}
		out, err := Put(src, "x.tf", target, lifted)
		if err != nil {
			t.Fatalf("Put: %v\n%s", err, src)
		}
		if !bytes.Equal(out, src) {
			t.Fatalf("put(lift(c), c) != c\ncode:\n%s\nafter put:\n%s", src, out)
		}
	})
}

func TestLawFidelity(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		src := mutate(t, mustRender(t, genResource(t)))
		desired := genResource(t)
		out, err := Put(src, "x.tf", target, desired)
		var conflict *ConflictError
		if errors.As(err, &conflict) {
			return // a block with hand-written content would have to go; nothing changed
		}
		if err != nil {
			t.Fatalf("Put: %v\n%s", err, src)
		}
		lifted, _, err := Lift(out, "x.tf", target, desired)
		if err != nil {
			t.Fatalf("Lift after Put: %v\n%s", err, out)
		}
		if diff := Changed(lifted, desired); len(diff) > 0 {
			t.Fatalf("lift(put(v, c)) differs from v at %v\ncode:\n%s\nafter put:\n%s", diff, src, out)
		}
		// Hand-written content survives. In canonically formatted files the
		// alignment around "=" may change, so whitespace is normalized.
		kept := map[string]bool{}
		for _, line := range strings.Split(string(out), "\n") {
			kept[normalize(line)] = true
		}
		for _, line := range strings.Split(string(src), "\n") {
			if strings.Contains(line, "var.") || strings.Contains(line, "nodr:keep") || strings.Contains(line, "extra") || strings.Contains(line, "serial") || strings.Contains(line, "by hand") {
				if !kept[normalize(line)] && !kept[normalize(singleLineBlock.ReplaceAllString(line, "$1"))] {
					t.Fatalf("hand-written line %q was lost\ncode:\n%s\nafter put:\n%s", line, src, out)
				}
			}
		}
		// Put edits only the values it has to change, so attributes
		// formatted by hand keep their formatting, even when their value
		// changes.
		for _, line := range strings.Split(string(out), "\n") {
			if strings.Contains(line, handFormatted) && !handFormattedLine.MatchString(line) {
				t.Fatalf("Put reformatted the line %q\ncode:\n%s\nafter put:\n%s", line, src, out)
			}
		}
		again, err := Put(out, "x.tf", target, desired)
		if err != nil || !bytes.Equal(again, out) {
			t.Fatalf("Put is not idempotent: %v\nfirst:\n%s\nsecond:\n%s", err, out, again)
		}
		if isFormatted(src) && !isFormatted(out) {
			t.Fatalf("Put broke the formatting\ncode:\n%s\nafter put:\n%s", src, out)
		}
	})
}

// singleLineBlock matches a block written on one line and captures its
// content, which Put may spread over several lines.
var singleLineBlock = regexp.MustCompile(`^\s*[a-z_]+ \{ (.*) \}$`)

// normalize removes the whitespace that canonical formatting controls.
func normalize(line string) string {
	return strings.Join(strings.Fields(strings.ReplaceAll(line, "=", " = ")), " ")
}

func mustRender(t *rapid.T, v testResource) []byte {
	src, err := Render(target, "", v)
	if err != nil {
		t.Fatal(err)
	}
	return src
}
