package hclmap

import (
	"errors"
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclsyntax"

	"github.com/centopw/nodr/internal/lens"
)

// ErrTargetNotFound reports that a file has no block matching a target.
var ErrTargetNotFound = errors.New("block not found")

// Target identifies a top-level block, such as
// resource "proxmox_virtual_environment_vm" "web_01".
type Target struct {
	Type   string
	Labels []string
}

// String formats the target as it appears in HCL.
func (t Target) String() string {
	var b strings.Builder
	b.WriteString(t.Type)
	for _, l := range t.Labels {
		fmt.Fprintf(&b, " %q", l)
	}
	return b.String()
}

// State is the ownership of one attribute or block in code.
type State struct {
	// Path is the path in code, such as cpu.cores or disk[1].size.
	Path   string
	Owner  lens.Owner
	Reason string
	// Line is the 1-based line in the file, or 0 if the code does not set
	// the attribute or block.
	Line int
}

// Reasons reported for code-owned fields.
const (
	ReasonExpression   = "set by an expression"
	ReasonPinned       = "pinned with " + PinComment
	ReasonDefault      = "not set in code, so the provider default applies"
	ReasonDynamic      = "generated by a dynamic block"
	ReasonDuplicate    = "the block is defined more than once"
	ReasonMetaArgument = "the resource uses count or for_each"
)

// metaArguments turn a resource into several instances, which a single
// intent resource cannot describe.
var metaArguments = []string{"count", "for_each"}

// Lift reads the target block of src into a copy of base. Synced fields take
// their values from the code; all other fields keep the values from base.
// It returns the ownership of every field the struct describes and of every
// extension in the block.
func Lift[T any](src []byte, filename string, target Target, base T) (T, []State, error) {
	var zero T
	file, diags := hclsyntax.ParseConfig(src, filename, hcl.InitialPos)
	if diags.HasErrors() {
		return zero, nil, fmt.Errorf("parse %s: %w", filename, diags)
	}
	block := findBlock(file.Body.(*hclsyntax.Body), target)
	if block == nil {
		return zero, nil, fmt.Errorf("%s in %s: %w", target, filename, ErrTargetNotFound)
	}
	sc, err := schemaOf(reflect.TypeOf(base))
	if err != nil {
		return zero, nil, err
	}
	out := deepCopy(reflect.ValueOf(base))
	l := lifter{src: src}
	if arg := metaArgument(block.Body); arg != nil {
		l.allCodeOwned(sc, "", arg.SrcRange.Start.Line, ReasonMetaArgument)
		return out.Interface().(T), l.states, nil
	}
	l.body(sc, block.Body, out, "")
	return out.Interface().(T), l.states, nil
}

type lifter struct {
	src    []byte
	states []State
}

func (l *lifter) add(path string, owner lens.Owner, reason string, line int) {
	l.states = append(l.states, State{Path: path, Owner: owner, Reason: reason, Line: line})
}

func (l *lifter) body(sc *structSchema, body *hclsyntax.Body, dst reflect.Value, prefix string) {
	for _, f := range sc.fields {
		if f.kind == attrField {
			l.attr(f, body.Attributes[f.name], dst.Field(f.index), join(prefix, f.name))
		}
	}
	for _, attr := range sortedAttributes(body) {
		if f, ok := sc.byName[attr.Name]; !ok || f.kind != attrField {
			l.add(join(prefix, attr.Name), lens.Extension, "", attr.SrcRange.Start.Line)
		}
	}

	byType, dynamic := groupBlocks(body)
	for _, f := range sc.fields {
		if f.kind == attrField {
			continue
		}
		path := join(prefix, f.name)
		if dyn, ok := dynamic[f.name]; ok {
			l.allCodeOwned(f.elem, path, dyn.TypeRange.Start.Line, ReasonDynamic)
			continue
		}
		blocks := byType[f.name]
		switch f.kind {
		case blockField:
			l.single(f, blocks, dst.Field(f.index), path)
		case blockListField:
			l.list(f, blocks, dst.Field(f.index), path)
		}
	}
	for _, b := range body.Blocks {
		if b.Type == "dynamic" {
			if len(b.Labels) > 0 {
				if f, ok := sc.byName[b.Labels[0]]; ok && f.kind != attrField {
					continue
				}
			}
			l.add(join(prefix, "dynamic."+strings.Join(b.Labels, ".")), lens.Extension, "", b.TypeRange.Start.Line)
			continue
		}
		if f, ok := sc.byName[b.Type]; !ok || f.kind == attrField {
			l.add(join(prefix, b.Type), lens.Extension, "", b.TypeRange.Start.Line)
		}
	}
}

func (l *lifter) attr(f *field, attr *hclsyntax.Attribute, dst reflect.Value, path string) {
	if attr == nil {
		l.absent(f, dst, path)
		return
	}
	line := attr.SrcRange.Start.Line
	val, ok := literal(attr.Expr)
	switch {
	case !ok:
		l.add(path, lens.CodeOwned, ReasonExpression, line)
	case pinned(l.src, attr.SrcRange):
		l.add(path, lens.CodeOwned, ReasonPinned, line)
	case val.IsNull():
		l.absent(f, dst, path)
	default:
		gv, err := fromCty(val, f)
		if err != nil {
			l.add(path, lens.CodeOwned, fmt.Sprintf("the value is not a valid %s", f.ctyType.FriendlyName()), line)
			return
		}
		dst.Set(gv)
		l.add(path, lens.Synced, "", line)
	}
}

// absent handles an attribute that the code does not set.
func (l *lifter) absent(f *field, dst reflect.Value, path string) {
	if !f.optional {
		l.add(path, lens.CodeOwned, ReasonDefault, 0)
		return
	}
	dst.Set(reflect.Zero(dst.Type()))
	l.add(path, lens.Synced, "", 0)
}

func (l *lifter) single(f *field, blocks []*hclsyntax.Block, dst reflect.Value, path string) {
	switch len(blocks) {
	case 0:
		if !f.optional {
			l.allCodeOwned(f.elem, path, 0, ReasonDefault)
			return
		}
		dst.Set(reflect.Zero(dst.Type()))
		l.add(path, lens.Synced, "", 0)
	case 1:
		if dst.IsNil() {
			dst.Set(reflect.New(f.elem.typ))
		}
		l.add(path, lens.Synced, "", blocks[0].TypeRange.Start.Line)
		l.body(f.elem, blocks[0].Body, dst.Elem(), path)
	default:
		l.allCodeOwned(f.elem, path, blocks[1].TypeRange.Start.Line, ReasonDuplicate)
	}
}

func (l *lifter) list(f *field, blocks []*hclsyntax.Block, dst reflect.Value, path string) {
	line := 0
	if len(blocks) > 0 {
		line = blocks[0].TypeRange.Start.Line
	}
	l.add(path, lens.Synced, "", line)
	if len(blocks) == 0 {
		dst.Set(reflect.Zero(dst.Type()))
		return
	}
	items := reflect.MakeSlice(dst.Type(), len(blocks), len(blocks))
	for i, b := range blocks {
		if i < dst.Len() {
			items.Index(i).Set(dst.Index(i))
		}
		l.body(f.elem, b.Body, items.Index(i), indexed(path, i))
	}
	dst.Set(items)
}

// allCodeOwned reports every attribute described by sc, below path, as
// code-owned.
func (l *lifter) allCodeOwned(sc *structSchema, path string, line int, reason string) {
	if path != "" {
		l.add(path, lens.CodeOwned, reason, line)
	}
	for _, f := range sc.fields {
		p := join(path, f.name)
		if f.kind == attrField {
			l.add(p, lens.CodeOwned, reason, line)
			continue
		}
		l.allCodeOwned(f.elem, p, line, reason)
	}
}

func findBlock(body *hclsyntax.Body, t Target) *hclsyntax.Block {
	for _, b := range body.Blocks {
		if b.Type == t.Type && equalLabels(b.Labels, t.Labels) {
			return b
		}
	}
	return nil
}

func equalLabels(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func metaArgument(body *hclsyntax.Body) *hclsyntax.Attribute {
	for _, name := range metaArguments {
		if a := body.Attributes[name]; a != nil {
			return a
		}
	}
	return nil
}

// groupBlocks returns the nested blocks of body by type, in source order,
// and the first dynamic block for each generated type.
func groupBlocks(body *hclsyntax.Body) (map[string][]*hclsyntax.Block, map[string]*hclsyntax.Block) {
	byType := map[string][]*hclsyntax.Block{}
	dynamic := map[string]*hclsyntax.Block{}
	for _, b := range body.Blocks {
		if b.Type == "dynamic" {
			if len(b.Labels) > 0 {
				if _, seen := dynamic[b.Labels[0]]; !seen {
					dynamic[b.Labels[0]] = b
				}
			}
			continue
		}
		byType[b.Type] = append(byType[b.Type], b)
	}
	return byType, dynamic
}

func sortedAttributes(body *hclsyntax.Body) []*hclsyntax.Attribute {
	attrs := make([]*hclsyntax.Attribute, 0, len(body.Attributes))
	for _, a := range body.Attributes {
		attrs = append(attrs, a)
	}
	sort.Slice(attrs, func(i, j int) bool { return attrs[i].SrcRange.Start.Byte < attrs[j].SrcRange.Start.Byte })
	return attrs
}
