{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodr.fullname" . }}-secret
  labels:
    {{- include "nodr.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.kek }}
  nodr-kek: {{ .Values.secret.kek | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.bootstrapToken }}
  nodr-bootstrap-token: {{ .Values.secret.bootstrapToken | b64enc | quote }}
  {{- end }}
{{- end }}
